### ISSUE TITLE
Cannot redeclare Amranidev\Laracombee\AbstractRecombee::listItemViewPortions()

### ISSUE THREAD

**Issue by laravel-vesuvius** [amranidev/laracombee#37]
I've got this error when ran: `php artisan laracombee:migrate user`.
After some diving in codebase i found in file: `AbstractRecombee.php` duplicate methods at lines: 671, 691. So maybe you need to fix line 691:
`public function listItemViewPortions($userId)`
to:
`public function listItemUserPortions($userId)`

**Comment by amranidev** [comment]
Fixed, upgrade laracombee to the latest release
