### ISSUE TITLE
Manage multiple databases

### ISSUE THREAD

**Issue by laravel-vesuvius** [amranidev/laracombee#38]
Does it possible to connect to several databases. As I understand, I need to register two Laracombee instances for this, am I right?. Otherwise how it will be better to implement this behaviour?

**Comment by amranidev** [comment]
At the moment, you can't do that with this current release.

Looks like a good idea to make this integration capable to connect to serval databases.

**Comment by amranidev** [comment]
Added in `v0.1.31`

You can create a new Laracombee class with `php artisan laracombee:new <ClassName>`, it will create a new Laracombee class in `app/Laracombee` directory.
It's recommended to create a `Facade` for the created class to keep it consistent.
