### ISSUE TITLE
How to initialize the Laracombee model to be used in another controller

### ISSUE THREAD

**Issue by waynegakuo** [amranidev/laracombee#42]
Hello Amrani,
I kindly need some help. I would like to call the "Laracombee::<method>" in a different controller so that I can be able to store interactions. From my experience, if we would like to use an instance of a model say 'Products', we usually add 'use App\Product' at the beginning of the controller file. How can we do so then in this case for Laracombee?

**Comment by amranidev** [comment]
@waynegakuo yes, you can use `Laracombee::` in any controller, just make sure to specify the `item` (base model class) in the configuration file, `config/laracombee.php`.

**Comment by waynegakuo** [comment]
I've done that as shown below:
`'item'  => app(\App\Purchase::class),`

So I want to add the interaction in controller but when I call 'Laracombee::ddPurchase($user_id, $item_id)'
I get this error:
`Class 'App\Http\Controllers\Laracombee' not found`

**Comment by amranidev** [comment]
Add `use Laracombee;` to the controller, since Laracombee is an alias

**Comment by waynegakuo** [comment]
Ok done it.

New error: `Call to undefined method Amranidev\Laracombee\Laracombee::addDetailView()`

**Comment by amranidev** [comment]
Method `addDetailView` doesn't exists, try `addDetailedView`

**Comment by amranidev** [comment]
@waynegakuo I've just released an update for this, can you please upgrade Laracombee to `v0.1.35`

**Comment by waynegakuo** [comment]
Sure. How do you update it though? What's the command?

**Comment by amranidev** [comment]
1. `composer update amranidev/laracombee`

2. `$options` is an optional array where you can specify more option in the request, such as `duration` of the `detail view` and the `timestamp` but those are optional not required.

3. At the moment, you can pass `$options` as an empty array `[]`.

**Comment by waynegakuo** [comment]
Sure. It's perfectly working. 
Issue is that it's not logging the interaction to the Recombee catalog listings. Maybe I forgot to include something?

**Comment by amranidev** [comment]
I think you forget to send the request

```php
$request = Laracombee::addDetailView($user_id, $item_id);
Laracombee::send($request)->wait();
```
