### ISSUE TITLE
Cannot use object of type GuzzleHttp\Promise\Promise as array

### ISSUE THREAD

**Issue by waynegakuo** [amranidev/laracombee#44]
I just ran into another issue with regards to providing recommendations. This is the statement I put in code:
`$user = User::findOrFail( $user_id);`

        // Prepare the request for recombee server, we need 10 recommended items for a given user.
        `$recommendations = Laracombee::recommendTo($user, $limit, $option);`

        `$itemsIds = $recommendations['recomms'];`

        `$items = \App\Product::find($itemsIds);`

And this is the error I get:
`Cannot use object of type GuzzleHttp\Promise\Promise as array`

**Comment by amranidev** [comment]
Hi @waynegakuo Sorry for the delay

`recommendTo` returns a promise, so you need to trigger `->wait()` method
