### ISSUE TITLE
Using multiple Models as Item(s)

### ISSUE THREAD

**Issue by flearsnetwork** [amranidev/laracombee#45]
Hi there,

Is there any intended way of using multiple Eloquent models as Recombee items instead of a single one with a single DB?

Thanks!

**Comment by amranidev** [comment]
Yes you can, you can create a new `Laracombee` class, `php artisan laracombee:new <ClassName>`
you are free to add a laraval facade to it or not, it's entirely up to you.

### Gotchas

1 - Make sure that this class has the correct env variables `database and token` of the second database.

2 - If you want to use laracombee artisan commands for the second Database, make sure to specify Eloquent models you want to use in `config/laracombee.php`

That should do it, please let me know if you find any issue

**Comment by flearsmedia** [comment]
Thank you for the fast answer!

Going that route, is it possible to get recommendations across models?

For example when having an "Ad" & and a "Book" is it possible to get Ad recommendations on the Book model based on a database column 'tags'?

**Comment by amranidev** [comment]
@flearsmedia I didn't understand your question
