### ISSUE TITLE
No laracombee.php in config

### ISSUE THREAD

**Issue by maidul98** [amranidev/laracombee#46]
how do i generate the laracombee.php in app/config file to add the database details?

**Comment by amranidev** [comment]
Hi @maidul98, you can run 
`php artisan vendor:publish --provider=Amranidev\Laracombee\Providers\LaracombeeServiceProvider`

**Comment by mushonnip** [comment]
> Hi @maidul98, you can run
> `php artisan vendor:publish --provider=Amranidev\Laracombee\Providers\LaracombeeServiceProvider`

I got this error and config file is not generated
```
Unable to locate publishable resources.
Publishing complete.
```

**Comment by FitriMakmor** [comment]
> > Hi @maidul98, you can run
> > `php artisan vendor:publish --provider=Amranidev\Laracombee\Providers\LaracombeeServiceProvider`
> 
> I got this error and config file is not generated
> 
> ```
> Unable to locate publishable resources.
> Publishing complete.
> ```

Add quotation marks between the provider as such
`php artisan vendor:publish --provider="Amranidev\Laracombee\Providers\LaracombeeServiceProvider"`
