### ISSUE TITLE
Class 'Amranidev\Laracombee\facades\LaracombeeFacade' not found

### ISSUE THREAD

**Issue by maidul98** [amranidev/laracombee#47]
I have my Laravel on Heroku and when I push it out to Heroku it gives me this. However, it works fine on localhost. Any ideas?

```
In AliasLoader.php line 80:
                                                                   
  Class 'Amranidev\Laracombee\facades\LaracombeeFacade' not found 

```

**Comment by amranidev** [comment]
Can you provide more details?

**Comment by maidul98** [comment]
> Can you provide more details?

In the terminal I run the following command to migrate the users:

heroku run php artisan laracombee:migrate user

Once I run this, I get this error:
```In AliasLoader.php line 80: Class 'Amranidev\Laracombee\facades\LaracombeeFacade' not found```

**Comment by amranidev** [comment]
#48
