### ISSUE TITLE
Adding items does not work

### ISSUE THREAD

**Issue by giojkd** [amranidev/laracombee#51]
Gave a look a the code but I couldn't figur out why. Using native apis works perfetly.

**Comment by giojkd** [comment]
Found out not working with laravel 7

**Comment by nguyenmiinh0208** [comment]
> Gave a look a the code but I couldn't figur out why. Using native apis works perfetly.

I am facing this issue. Where are native apis ? Please give me an advance !

**Comment by amranidev** [comment]
@giojkd / @nguyenmiinh0208  , I've updated the package with the latest recombee sdk v4, feel free to try again with the latest version of this package.
NOTE: the main API didn't change, only some configurations needs to be applied.
