### ISSUE TITLE
Error on seed command

### ISSUE THREAD

**Issue by IuliaCovalenco94** [amranidev/laracombee#52]
Hi @amranidev . Thank you so much for your module!
However i'm having some trouble with seed command. I'mn getting an error, which is 

{"message": "Invalid (not found) path for request #0; batch not executed"}.
 i reaaly cannot find the error

Thank you!

**Comment by IuliaCovalenco** [comment]
Hi @amranidev still unable to resolve the issue. Can you help me ? Thank you!

**Comment by amranidev** [comment]
@IuliaCovalenco94 / @IuliaCovalenco , I've updated the package with the latest recombee sdk v4, feel free to try again with the latest version of this package.
NOTE: the main API didn't change, only some configurations needs to be applied.
